apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagecontentsourcepolicies.operator.openshift.io
spec:
  group: operator.openshift.io
  scope: Cluster
  names:
    kind: ImageContentSourcePolicy
    singular: imagecontentsourcepolicy
    plural: imagecontentsourcepolicies
    listKind: ImageContentSourcePolicyList
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Standard object's metadata.
          type: object
        spec:
          description: spec holds user settable values for configuration
          properties:
            repositoryDigestMirrors:
              description: repositoryDigestMirrors allows images referenced by image
                digests in pods to be pulled from alternative mirrored repository
                locations. The image pull specification provided to the pod will be
                compared to the source locations described in RepositoryDigestMirrors
                and the image may be pulled down from any of the repositories in the
                list instead of the specified repository allowing administrators to
                choose a potentially faster mirror. Only image pull specifications
                that have an image disgest will have this behavior applied to them
                - tags will continue to be pulled from the specified repository in
                the pull spec. When multiple policies are defined, any overlaps found
                will be merged together when the mirror rules are written to `/etc/containers/registries.conf`.
                For example, if policy A has sources `a, b, c` and policy B has sources
                `c, d, e`. Then the mirror rule written to `registries.conf` will
                be `a, b, c, d, e` where the duplicate `c` is removed.
              items:
                properties:
                  sources:
                    description: sources are repositories that are mirrors of each
                      other.
                    items:
                      type: string
                    type: array
                type: object
              type: array
          type: object
      required:
      - spec
