apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: config-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
