apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.config.openshift.io
spec:
  group: config.openshift.io
  scope: Cluster
  names:
    kind: Registry
    singular: registry
    plural: registries
    listKind: RegistryList
  versions:
    - name: v1
      served: true
      storage: true
