apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: config-operator-serving-cert
  labels:
    app: config-operator
  name: metrics
  namespace: openshift-config-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: config-operator
  sessionAffinity: None
  type: ClusterIP
