apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: images.config.openshift.io
spec:
  group: config.openshift.io
  version: v1
  scope: Cluster
  names:
    kind: Image
    singular: image
    plural: images
    listKind: ImageList
